STATUS_TEST : cubestatus.test.cpp
	g++ cubestatus.test.cpp -std=c++11 -o cubestatus.exe
	./cubestatus.exe

SOLVER_TEST : cubesolver.test.cpp
	g++ cubesolver.test.cpp -std=c++11 -o cubesolver.exe
	./cubesolver.exe

GENERATOR : cube.generator.cpp
	g++ cube.generator.cpp -std=c++11 -o cube.generator.exe
